name: MainTests

# Controls when the workflow will run
on:
 [push]

jobs:
  test:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    # sequence of tasks that will be executed as part of the job
    steps:

      #Check out to the develop branch
      - name: Checkout dev
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      #Install node.js
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
        
      #Install yarn
      - name: Install yarn
        run: npm install yarn -g
        
      - name: Install packages
        run: yarn install

      # - name: Wait for containers startup
      #   run: sleep 2m
      #   shell: bash

      #Run tests on the entire repository
      - name: Test
        run: |
          yarn nx run-many --target=test --all --skip-nx-cache --parallel --coverage
        #yarn nx run-many --target=build --all --skip-nx-cacahe --parallel
        #yarn nx run-many --target=lint --all --skip-nx-cache --parallel
        #yarn nx run-many --target=e2e --all --skip-nx-cache --parallel --coverage
